[package]
name = "crabby_space_institute"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
bevy = "0.19"
bevy_egui = "0.41"
directories = "6"
mlua = { version = "0.12", features = ["lua54", "vendored", "serde", "send"] }
ron = "0.12"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
approx = "0.5"
